// <auto-generated />
using System;
using FundAdministration.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FundAdministration.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FundAdministration.Core.Funds.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Funds", (string)null);
                });

            modelBuilder.Entity("FundAdministration.Core.Investors.Investor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("Investors", (string)null);
                });

            modelBuilder.Entity("FundAdministration.Core.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("FundAdministration.Core.Funds.Fund", b =>
                {
                    b.OwnsOne("FundAdministration.Core.Funds.Currency", "Currency", b1 =>
                        {
                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("CurrencyCode");

                            b1.HasKey("FundId");

                            b1.ToTable("Funds");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.Navigation("Currency")
                        .IsRequired();
                });

            modelBuilder.Entity("FundAdministration.Core.Investors.Investor", b =>
                {
                    b.HasOne("FundAdministration.Core.Funds.Fund", "Fund")
                        .WithMany("Investors")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FundAdministration.Core.Investors.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("InvestorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmailId")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("EmailId");

                            b1.HasKey("InvestorId");

                            b1.ToTable("Investors");

                            b1.WithOwner()
                                .HasForeignKey("InvestorId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FundAdministration.Core.Transactions.Transaction", b =>
                {
                    b.HasOne("FundAdministration.Core.Investors.Investor", "Investor")
                        .WithMany("Transactions")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("FundAdministration.Core.Funds.Fund", b =>
                {
                    b.Navigation("Investors");
                });

            modelBuilder.Entity("FundAdministration.Core.Investors.Investor", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
